#!/bin/bash

umask 002
# echo timestamp $(date +%s)

#----------------------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#----------------------------------------------------------------#

echo "-------------------------------------------"
echo "* step4 submitted at `date +%FT%H.%M.%S`"
echo "-------------------------------------------"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
# echo "* STEP4_ANT_LAB:        $STEP4_ANT_LAB"
echo "* SCRNA_METHOD:         ${SCRNA_METHOD}"
echo "-------------------------------------------"
echo "------Parameters used to run this step-----"
cat  $OUTPUT_DIR/job_info/parameters/step4_par.txt
# echo "Anti Label used:"
# cat  $OUTPUT_DIR/job_info/parameters/step4_antibody_label.txt
echo "-------------------------------------------"
echo -e "------Output of Run------------------------\n\n"

#----------------------------------------------------------------#
# START PIPELINE                                      #
#----------------------------------------------------------------#

module load r/$R_VERSION
Rscript ${PIPELINE_HOME}/hto/scripts/step4/hto_step4.R $OUTPUT_DIR  $R_LIB_PATH 





