site_name: scRNAbox
site_url: https://neurobioinfo.github.io/
nav:
    - Home: index.md
    - Installation: installation.md
    - Overview:
        - '- Standard Analysis Track' : SCRNA.md
        - '- Cell Hashtag Analysis Track' : HTO.md
        - '- Execution parameters' : reference.md 
        - '- Outputs': outputs.md
        
    - Tutorial:
        - '- Standard Analysis: Midbrain dataset' : Dataset1.md
        - '- Cell Hashtag Analysis: PBMC dataset' : Dataset2.md
        - '- Processed Data' : PROC.md
        - '- Library preparation' : library_prep.md

    - FAQ : FAQ.md        
           
    - About:
        - '- License': 'LICENSE.md'
        - '- Changelog': 'changelog.md'
        - '- Contributing': contributing.md
        - '- Acknowledgement': Acknowledgement.md
theme: readthedocs
