#!/bin/bash

#PBS -l walltime=168:0:0
#PBS -r n
#PBS -j oe
#PBS -W umask=002

umask 002
echo timestamp $(date +%s)


#-----------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#-----------------------------------------------------#
# if [ -z $SAMPLE ]; then echo "ERROR: you must supply SAMPLE variable as -v to qsub"; exit 42; fi
# if [[ -f $DIR ]]; then echo "ERROR: you must supply DIR variable as -v to qsub"; exit 42; fi
# if [[ -z $THREADS ]]; then echo "ERROR: you must supply THREADS variable as -v to qsub"; exit 42; fi
# if [[ -z $MAX_MEM ]]; then echo "ERROR: you must supply MAX_MEM variable as -v to qsub"; exit 42; fi
# if [[ -z $PIPELINE_HOME ]]; then echo "ERROR: you must supply PIPELINE_HOME variable as -v to qsub"; exit 42; fi
# if [[ -z $BAM ]]; then echo "ERROR: you must supply BAM variable as -v to qsub"; exit 42; fi
# if [[ -z $DONE ]]; then echo "ERROR: you must supply DONE variable as -v to qsub"; exit 42; fi
# if [[ -z $SFS ]]; then export SFS=0; fi

echo "*******************************************"
echo "* step4"
echo "*******************************************"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
# echo "* nFeature_RNA Lower:              $NFRNAL"
# echo "* nFeature_RNA Upper:              $NFRNAU"
# echo "* percent.mt:        $PMT"
# echo "* BAM:                  $BAM"
# echo "* SFS                   $SFS"
# echo "* VERBOSE               $VERBOSE"
# echo "* DONE:                 $DONE"
echo "*******************************************"

#-----------------------------------------------------#
# START PIPELINE                                      #
#-----------------------------------------------------#
# cd $DIR

# DIR=/home/samamiri/scratch/Darkgenome_run/pipeline/scrnabox.svn_run/des
# cd /home/samamiri/scratch/Darkgenome_run/pipeline/scrnabox.svn/scripts/step2/
module load r/4.1.2 
Rscript ${PIPELINE_HOME}/scripts/step6/step6.R $OUTPUT_DIR  $R_LIB_PATH

echo "step6 is done succefully  at `date +%FT%H.%M.%S`" 
