#!/bin/bash

umask 002
echo timestamp $(date +%s)

#----------------------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#----------------------------------------------------------------#

echo "-------------------------------------------"
echo "* step6 submitted at `date +%FT%H.%M.%S`"
echo "-------------------------------------------"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
echo "* SCRNA_METHOD:         ${SCRNA_METHOD}"
echo "-------------------------------------------"
echo "------Parameters used to run this step-----"
cat  $OUTPUT_DIR/job_info/parameters/step6_par.txt
echo "-------------------------------------------"
#----------------------------------------------------------------#
# START PIPELINE                                      #
#----------------------------------------------------------------#

module load r/$R_VERSION
Rscript ${PIPELINE_HOME}/hto/scripts/step6/hto_step6.R $OUTPUT_DIR  $R_LIB_PATH
