#!/bin/bash

umask 002

#----------------------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#----------------------------------------------------------------#

echo "-------------------------------------------"
echo "step7 markergsea submitted at `date +%FT%H.%M.%S`" 
echo "-------------------------------------------"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
echo "* SCRNA_METHOD:                  ${SCRNA_METHOD}"
echo "-------------------------------------------"
echo "------Parameters used in this step---------"
cat  $OUTPUT_DIR/job_info/parameters/step7_par.txt
echo "-------------------------------------------"
echo -e "------Output of Run------------------------\n\n"
#----------------------------------------------------------------#
# START PIPELINE                                      #
#----------------------------------------------------------------#

module load r/$R_VERSION 
Rscript ${PIPELINE_HOME}/hto/scripts/step7/hto_step7_markergsea.R $OUTPUT_DIR  $R_LIB_PATH $PIPELINE_HOME
