#!/bin/bash

umask 002



#----------------------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#----------------------------------------------------------------#

echo "-------------------------------------------"
echo "* step2 submitted at `date +%FT%H.%M.%S`"
echo "-------------------------------------------"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* OUTPUT DIR:                  $OUTPUT_DIR"
echo "* R LIB PATH:                  $R_LIB_PATH"
echo "* scRNA method:          $SCRNA_METHOD"
echo "-------------------------------------------"


#----------------------------------------------------------------#
# START PIPELINE                                      #
#----------------------------------------------------------------#

module load r/$R_VERSION 
Rscript ${PIPELINE_HOME}/scrna/scripts/step2/scrna_step2.R  $OUTPUT_DIR  $R_LIB_PATH 

