#!/bin/bash


umask 002
# echo timestamp $(date +%s)


#----------------------------------------------------------------#
#                                                     #
# INITIALIZE VARIABLES                                #
#                                                     #
#----------------------------------------------------------------#
echo "-------------------------------------------"
echo "* step8 addmeta `date +%FT%H.%M.%S`"
echo "-------------------------------------------"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
echo "* scRNA method:          $SCRNA_METHOD"
echo "-------------------------------------------"
echo "------Parameters used in this step---------"
cat  $OUTPUT_DIR/job_info/parameters/step8_par.txt
echo "-------------------------------------------"
echo -e "------Output of Run------------------------\n\n"
#----------------------------------------------------------------#
# START PIPELINE                                      #
#----------------------------------------------------------------#

module load r/$R_VERSION
Rscript ${PIPELINE_HOME}/hto/scripts/step8/hto_step8_addmeta.R $OUTPUT_DIR  $R_LIB_PATH $PIPELINE_HOME
